name: zaart
author: Sepehr Aryani
homepage: https://github.com/sepisoad/zaart
version: 0.0.1
description: a dead simple static site generator (for dart)

dependencies:
  logging: ^0.11.3+2
  test: ^1.5.1
  args: ^1.5.0
  markdown: ^2.0.2
  mustache: ^1.0.2